export { generateReference } from "./reference.js";
export { generateVideo } from "./video.js";
export { extractFrames, dedupeFrames, detectLoopWindow, applyLoopWindow } from "./frames.js";
export { matteFrames, smoothMattes } from "./matte.js";
export { normalizeFrames, pixelSnap, anchorModeFor } from "./normalize.js";
export { packSheet } from "./pack.js";
export { measureSeams, sliceTiles } from "./tileset.js";
export { unspool, DEFAULT_RIG_PIXEL_HEIGHT } from "./orchestrate.js";
export { generatePartsSheet } from "./parts.js";
export { segmentParts, isolateLargestBlob } from "./segment.js";
export { fitToSkeleton } from "./fit.js";
export type { RigOverrides, FitInput, FitResult } from "./fit.js";
export { bakeClips, renderCommands } from "./bake.js";
export type { BakeOptions, EquippedArt } from "./bake.js";
export { generateEquipmentArt, fitEquipment } from "./equipment.js";
