import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { ExportInput, ExportedFile, Exporter } from "../types.js";

export const cssExporter: Exporter = {
  id: "css",
  async export(input: ExportInput): Promise<ExportedFile[]> {
    await mkdir(input.outDir, { recursive: true });
    const { cell, size, fps } = input.manifest.meta;
    const css = `.${input.asset.id}-sprite {
  width: ${cell.w}px;
  height: ${cell.h}px;
  background-image: url("${input.sheetFileName}");
  background-repeat: no-repeat;
  image-rendering: pixelated;
  image-rendering: crisp-edges;
}
`;
    const js = `/** Dependency-free sheet player generated by unspooler. */
export const ${safeIdent(input.asset.id)}Sheet = ${JSON.stringify(
      {
        image: input.sheetFileName,
        cell,
        size,
        fps,
        tags: input.manifest.meta.frameTags,
        frames: input.manifest.frames.map((f) => ({
          name: f.filename,
          x: f.frame.x,
          y: f.frame.y,
          animation: f.animation,
          direction: f.direction,
          duration: f.duration,
        })),
      },
      null,
      2,
    )};

export function playUnspoolerSprite(el, sheet, tagName) {
  const tag = sheet.tags.find((t) => t.name === tagName) || sheet.tags[0];
  if (!tag) return () => {};
  const frames = sheet.frames.slice(tag.from, tag.to + 1);
  let i = 0;
  const id = setInterval(() => {
    const f = frames[i];
    el.style.backgroundPosition = \`-\${f.x}px -\${f.y}px\`;
    i = tag.loop ? (i + 1) % frames.length : Math.min(i + 1, frames.length - 1);
  }, 1000 / sheet.fps);
  return () => clearInterval(id);
}
`;
    const cssPath = join(input.outDir, `${input.asset.id}.css`);
    const jsPath = join(input.outDir, `${input.asset.id}.player.js`);
    await writeFile(cssPath, css);
    await writeFile(jsPath, js);
    return [
      { path: cssPath, contents: css },
      { path: jsPath, contents: js },
    ];
  },
};

function safeIdent(id: string): string {
  const cleaned = id.replace(/[^a-zA-Z0-9_]/g, "_");
  return /^[a-zA-Z_]/.test(cleaned) ? cleaned : `asset_${cleaned}`;
}
